# Generated by Django 3.1 on 2020-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200902_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Enter Language of the Book.', max_length=200),
        ),
    ]
