# Generated by Django 3.1 on 2020-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledAppsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=60)),
                ('app_location', models.CharField(max_length=100)),
                ('app_shorttext', models.TextField()),
            ],
        ),
    ]
